import { StyleSheet } from 'react-native';
import Dims from '../../utils/dimensions.js';

const resource_container_width = 450,
	resource_margin_left = 100;

const styles = StyleSheet.create({
	header:{
		width:Dims.width(1),
		alignItems:'center'
	},
	header_bg:{
		width:Dims.pixel(2078),
		height:Dims.pixel(259),
	},
	resource_img:{
		width:Dims.pixel(160),
		height:Dims.pixel(146)
	},
	resource_container:{
		height:Dims.pixel(146),
		width:Dims.pixel(resource_container_width),
		flexDirection:'row',
		position:'absolute',
		top:Dims.pixel(45)
	},
	resource_bg:{
		width:Dims.pixel(382),
		height:Dims.pixel(123),
		top:Dims.pixel(10),
		left:Dims.pixel(90),
		position:'absolute'
	},
	resource_gold:{
		left:Dims.pixel(resource_margin_left)
	},
	resource_crystal:{
		left:Dims.pixel(resource_margin_left+resource_container_width+180)
	},
	resource_text:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(85),
		color:'#ffffff',
		margin:Dims.pixel(10)
	},
	resource_plus_container:{
		position:'absolute',
		right:0,
		top:Dims.pixel(-5)
	},
	resource_plus:{
		fontFamily:'Gotham-Medium',
		color:'#8bd910',
		fontSize:Dims.pixel(110),
	},
	settings_container:{
		position:'absolute',
		right:Dims.pixel(75),
		top:Dims.pixel(10)
	},
	settings:{
		width:Dims.pixel(209),
		height:Dims.pixel(216)
	},
	title_container:{
		width:Dims.pixel(1455),
		height:Dims.pixel(207),
		position:'absolute',
		top:Dims.pixel(246),
		left:Dims.pixel(98)
	},
	title_guild:{
		position:'absolute',
		top:Dims.pixel(30),
		left:Dims.pixel(60)
	},
	title_guild_icon:{
		width:Dims.pixel(130),
		height:Dims.pixel(130)
	},
	title_nick_container:{
		position:'absolute',
		top:Dims.pixel(20),
		left:Dims.pixel(250),
		width:Dims.pixel(500)
	},
	title_nick:{
		fontFamily:'Gotham-Bold',
		color:'#fffbeb',
		fontSize:Dims.pixel(64),
		// textShadowColor: '#000000',
		// textShadowOffset: {width: 1, height: Dims.pixel(6)},
		// textShadowRadius: Dims.pixel(50)
	},
	title_nick_shadow:{
		fontFamily:'Gotham-Bold',
		color:'#7e1a47',
		fontSize:Dims.pixel(64),
		position:'absolute',
		top:Dims.pixel(6),
		left:Dims.pixel(-1)
	},
	title_guild_name:{
		fontFamily:'Gotham-Medium',
		color:'#dad2b0',
		fontSize:Dims.pixel(53),
		marginTop:Dims.pixel(-15)
	},
	title_goblet:{
		width:Dims.pixel(102),
		height:Dims.pixel(106),
		position:'absolute',
		top:Dims.pixel(42),
		left:Dims.pixel(1060)
	},
	title_trophy:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(85),
		color:'#ffe94d',
		position:'absolute',
		left:Dims.pixel(1195),
		top:Dims.pixel(36)
	},
	title_trophy_shadow:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(85),
		color:'#4a0a1b',
		position:'absolute',
		left:Dims.pixel(1194),
		top:Dims.pixel(40)
	},
	top_menu:{
		// height:Dims.pixel(146),
		width:Dims.width(1),
		flexDirection:'row',
		position:'absolute',
		top:Dims.pixel(460),
		// left:Dims.pixel(500),
		justifyContent:'center',
		alignItems:'center'
	},
	top_menu_el:{
		width:Dims.pixel(291),
		height:Dims.pixel(298),
		margin:Dims.pixel(1)
	},
	top_menu_counter:{
		width:Dims.pixel(106),
		height:Dims.pixel(114),
		top:Dims.pixel(190),
		left:Dims.pixel(190),
		justifyContent:'center',
		alignItems:'center'
	},
	top_menu_counter_text:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(75),
		color:'#ffffff',
		marginTop:Dims.pixel(-18),
		marginLeft:Dims.pixel(-10)
	},
	chests_container:{
		width:Dims.width(1),
		flexDirection:'row',
		position:'absolute',
		top:Dims.pixel(775),
		justifyContent:'center',
		alignItems:'center'
	},
	chest_container:{
		width:Dims.pixel(489),
		height:Dims.pixel(539)
	},
	chest:{
		position:'absolute',
		top:0,
		left:0
	},
	chest_timer_text:{
		fontFamily:'Gotham-Bold',
		fontSize:Dims.pixel(64),
		color:'#522f3a',
		top:Dims.pixel(28),
		left:Dims.pixel(170)
	},
	chest_open_text:{
		fontFamily:'Gotham-Bold',
		fontSize:Dims.pixel(37),
		color:'#a4fe17',
		position:'absolute',
		bottom:Dims.pixel(48),
		left:Dims.pixel(50),
		width:Dims.pixel(260)
	},
	chest_ruby:{
		width:Dims.pixel(80),
		height:Dims.pixel(79),
		position:'absolute',
		right:Dims.pixel(130),
		bottom:Dims.pixel(48)
	},
	//Kenyan Coffee Bold 85 #ffffff; shadow #232149 100% distance 4px spread 100% size 2px
	chest_ruby_container:{
		position:'absolute',
		bottom:Dims.pixel(50),
		right:Dims.pixel(0),
		height:Dims.pixel(100),
		width:Dims.pixel(160),
		alignItems:'center'
	},
	chest_ruby_count:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(85),
		color:'#ffffff',
		position:'absolute',
		top:0
	},
	chest_ruby_count_shadow:{
		fontFamily:'KenyanCoffeeRg-Bold',
		fontSize:Dims.pixel(88),
		color:'#232149',
		position:'absolute',
		top:Dims.pixel(3),
		marginLeft:Dims.pixel(-2)
	}
});

export default styles;